import { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties } = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '100vh',
    width: '100%',
    padding: '20px',
    boxSizing: 'border-box',
    backgroundColor: '#8BCF00',
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  output: {
    fontSize: '64px',
    wordWrap: 'break-word',
    maxWidth: '80vw',
    textAlign: 'center',
    marginBottom: '20px',
    transform: 'scale(0.8, 1.03)',
    filter: 'blur(1px) contrast(110%)',
    letterSpacing: '-0.5px',
  },
  controls: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    marginBottom: '10px',
  },
  input: {
    width: '300px',
    padding: '10px 15px',
    border: 'none',
    borderRadius: '25px',
    fontSize: '16px',
    outline: 'none',
    boxShadow: '0 2px 5px rgba(0,0,0,0.1)',
    transition: 'all 0.3s ease',
    marginBottom: '10px',
    backgroundColor: '#a3e600',
    color: '#333',
  },
  button: {
    backgroundColor: '#4a7a00',
    border: 'none',
    borderRadius: '25px',
    cursor: 'pointer',
    padding: '10px 20px',
    fontSize: '16px',
    color: '#fff',
    transition: 'all 0.3s ease',
    transform: 'scale(0.95, 1.05)',
    filter: 'blur(0.5px) contrast(120%)',
    letterSpacing: '1px',
  },
  footer: {
    fontSize: '24px',
    transform: 'scale(0.9, 1.03)',
    filter: 'blur(0.5px) contrast(110%)',
    letterSpacing: '-0.3px',
    marginTop: '20px',
  },
};