import { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties } = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '100%',
    width: '100%',
    padding: '20px',
    boxSizing: 'border-box',
  },
  output: {
    fontSize: '48px',
    wordWrap: 'break-word',
    maxWidth: '80vw',
    textAlign: 'center',
    marginBottom: '20px',
    transform: 'scale(0.8, 1.03)',
    filter: 'blur(1px) contrast(110%)',
    letterSpacing: '-0.5px',
  },
  controls: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginBottom: '10px',
  },
  input: {
    width: '300px',
    padding: '10px 15px',
    border: 'none',
    borderRadius: '25px',
    fontSize: '16px',
    outline: 'none',
    boxShadow: '0 2px 5px rgba(0,0,0,0.1)',
    transition: 'all 0.3s ease',
    marginRight: '10px',
  },
  button: {
    backgroundColor: '#66A100',
    border: 'none',
    borderRadius: '50%',
    cursor: 'pointer',
    padding: '10px',
    width: '44px',
    height: '44px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    transition: 'background-color 0.3s ease',
  },
  icon: {
    width: '24px',
    height: '24px',
    fill: 'white',
  },
  footer: {
    fontSize: '48px',
    transform: 'scale(0.8, 1.03)',
    filter: 'blur(1px) contrast(110%)',
    letterSpacing: '-0.5px',
  },
};